spring.application.name=orm-learn

logging.level.org.springframework=info
logging.level.com.cognizant=debug

logging.level.org.hibernate.SQL=debug

spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn
spring.datasource.username=root
spring.datasource.password=1112

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
